news:
  format: "&7[&c/!&7] {MESSAGE} &7[&c/!&7]"
  message: test

mute:
  mute-format: "{PLAYER}"
  unmute-format: "{PLAYER}"
spawn:
  minX: -385
  maxX: 385
  minZ: -385
  maxZ: 385
command-blacklist:
  - pl
  - plugins
  - ?
  - help

lucky-ore:
  gold-ore: 0.0
  iron-ore: 0.0
  coal-ore: 0.0
  lapis-ore: 0.0
  diamond-ore: 0.0
  redstone-ore: 0.0
  emerald-ore: 0.0
  quartz-ore: 0.0
  lignite-ore: 0.0
  zinc-ore: 0.0
  cronyxe-ore: 0.0
  kobalt-ore: 0.0
  eldarium-ore: 0.0
  gemme-ore: 0.0
  xp-ore: 0.0

repair-orb:
  # en ticks
  period: 100
  repair: 50