name: EldariaCommons
version: 1.0.0
description: Fonctionnalites d Eldaria
author: Dabsunter

main: fr.dabsunter.eldaria.commons.Main
depends: [Factions]

commands:
  newsset:
    description: Definir le message d acceuil
    aliases: [definir-la-news-d-acceuil-de-ses-morts, ns, newset]
    permission: eldaria.setnews
  mutechat:
    description: Mute le chat
    aliases: [unmutechat]
    permission: eldaria.mute.command
    usage: /<command>
  announce:
    description: Annoncer en haut de l ecran
    aliases: [annonce]
    permission: eldaria.announce
    usage: /<command> <duration> <message>
  announcebar:
    description: Annoncer en bas de l ecran
    aliases: [annoncebar]
    permission: eldaria.announce
    usage: /<command> <joueur>|@a [-duration=<duration>] [-rainbow] <message>
  bossbar:
    description: Annoncer dans la bossbar
    permission: eldaria.announce
    usage: /<command> <joueur>|@a [-duration=<duration>] [-progress=<progress>] <message>
  killstreak:
    description: Affiche les statistiques liées au kills du joueur
    aliases: [ks]
    usage: /<command> [joueur]
  topkillstreak:
    description: Affiche le top KillStreak
    aliases: [topks]
    usage: /<command> [joueur]
  mobstand:
    description: Permet de gérer des mobs sans IA
    aliases: [mobs]
    permission: eldaria.mobstand
    usage: /<command> spawn|remove

permissions:
  eldaria.setnews:
    default: op
  eldaria.mute.command:
    default: op
  eldaria.mute.chat:
    default: op
  eldaria.announce:
    default: op
  eldaria.mobstand:
    default: op